nof_usrp_dev: 1
usrp_setting_0:
  ssb_freq: 3488160000 #1989850000 #1970450000 #3489600000 #3649440000 #3650880000 # 1970450000 #2600040000 #3488160000 #3685440000 #3561600000 #1842050000 #2528550000 #3565920000 #2524950000 #2523750000 # 3565920000 # 2527350000 #3408960000  # should be set to the ssb frequency of the cell
  rf_args: "clock=external,type=x300,master_clock_rate=200000000,sampling_rate=25000000" #"type=x300" #"clock=external" for TwinRX
  # rf_args: "clock=external,type=x300,sampling_rate=23040000" #"type=x300" #"clock=external" for CBX
  rx_gain: 90 # for x310 CBX, max rx gain is 31.5, for b210, it's around 80, for x310 TwinRX, max rx gain is 90
  srate_hz: 25000000 #11520000 #11520000 #23040000 (CBX)
  srsran_srate_hz: 23040000
  nof_carriers: 1
  nof_antennas: 1
  scs_index: 1 #(0: 15kHz, 1: 30kHz, ..., the u in standard)
  rf_log_level: "debug"
  nof_rnti_worker_groups: 1
  nof_bwps: 2

  log_name: "a.csv" #"/home/wanhr/Documents/data/nrscope/evaluation/coverage_amarisoft/dci_tx_50.csv" # x (0-10), y(0-8) coordinates
  google_dataset_id: "ngscope5g_dci_log_wanhr"

# usrp_setting_1:
#   dl_freq: 3649440000 #3685440000 #3561600000 #1842050000 #2528550000 #3565920000 #2524950000 #2523750000 # 3565920000 # 2527350000 #3408960000  # should be set to the ssb frequency of the cell
#   rf_args: "serial=31993A8,clock=external,type=b200" #"type=x300" #"clock=external"
#   rx_gain: 30 # for x310, max rx gain is 31.5, for b210, it's around 80
#   srate_hz: 23040000
#   nof_carriers: 1
#   nof_antennas: 1
#   scs_index: 1 #(0: 15kHz, 1: 30kHz, ..., the u in standard)
#   rf_log_level: "debug"

#   log_name: "./b.csv"  
#   google_dataset_id: "ngscope5g_dci_log_wanhr"

log_config:
  local_log: true
  push_to_google: false
  google_service_account_credential: "/home/wanhr/Downloads/nsf-2223556-222187-02b924918c95.json"

